apiVersion: batch/v1
kind: Job
metadata:
  name: agent-kubectl
  labels:
    jenkins-agent: jnlp-agent-kubectl
spec:
  template:
    spec:
      containers:
      - name: kubectl
        image: bitnami/kubectl
        command: ["version"]
      restartPolicy: Never
  backoffLimit: 4