apiVersion: v1
kind: Pod
metadata:
  name: agent-nodejs
  labels:
      jenkins-agent: jnlp-agent-nodejs
spec:
  containers:
    - name: nodejs
      image: jenkins/jnlp-agent-node:16.10.0
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "1024Mi"
          cpu: "2000m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
