apiVersion: v1
kind: Pod
metadata:
  name: agent-kubectl
  labels:
      jenkins-agent: jnlp-agent-kubectl
      jenkins/label: agent-$JOB_NAME-$BUILD_NUMBER
spec:
  containers:
    - name: kubectl
      image: bitnami/kubectl
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
