apiVersion: v1
kind: Pod
metadata:
  name: agent-python3
  labels:
      jenkins-agent: jnlp-agent-nodejs
spec:
  containers:
    - name: nodejs
      image: jenkins/jnlp-agent-node:latest
      command:
        - cat
      tty: false
