apiVersion: v1
kind: Pod
metadata:
  name: agent-nodejs
  labels:
      jenkins-agent: jnlp-agent-nodejs
spec:
  containers:
    - name: nodejs
      image: jenkins/jnlp-agent-node:latest
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "400m"
