apiVersion: v1
kind: Pod
metadata:
  name: agent-kubectl
  labels:
      jenkins-agent: jnlp-agent-kubectl
spec:
  serviceAccountName: internal-kubectl
  containers:
    - name: kubectl
      image: bitnami/kubectl
      command: ['sleep', '60']
        #      command: ['kubectl']
        #args:
        #- apply
        #- -f
        #- https://raw.githubusercontent.com/StartloJ/ts-example/main/k8s/deployment.yaml
      tty: true
