apiVersion: v1
kind: Pod
metadata:
  name: agent-kubectl
  labels:
      jenkins-agent: jnlp-agent-kubectl
spec:
  serviceAccountName: jenkins
  containers:
    - name: kubectl
      image: bitnami/kubectl
      command: ['kubectl']
      args:
        - apply
        - -f
        - https://raw.githubusercontent.com/StartloJ/ts-example/main/k8s/deployment.yaml
      tty: true
      # resources:
      #   requests:
      #     memory: "128Mi"
      #     cpu: "100m"
      #   limits:
      #     memory: "256Mi"
      #     cpu: "200m"
