apiVersion: v1
kind: Pod
metadata:
  name: agent-ts-example
  labels:
      jenkins-agent: agent-ts-example
spec:
  containers:
    - name: ts-example
      image: piky/ts-example:latest
      command:
        - cat
      tty: true
      # resources:
      #   requests:
      #     memory: "256Mi"
      #     cpu: "100m"
      #   limits:
      #     memory: "512Mi"
      #     cpu: "400m"
