apiVersion: v1
kind: Pod
metadata:
  name: agent-kubectl
  labels:
      jenkins-agent: jnlp-agent-kubectl
spec:
  serviceAccountName: jenkins
  containers:
    - name: kubectl
      image: bitnami/kubectl
      command: ['kubectl']
      args:
        - get
        - pods
      tty: true
