apiVersion: v1
kind: Pod
metadata:
  name: agent-kubectl
  labels:
      jenkins-agent: jnlp-agent-kubectl
spec:
  containers:
    - name: kubectl
      image: yonadev/jnlp-slave-k8s-helm
      command: ['sleep', '300']
      tty: true
