apiVersion: v1
kind: Pod
metadata:
  name: buildkitd
spec:
  serviceAccountName: jenkins
  containers:
    - name: buildkitd
      image: piky/buildkit
      readinessProbe:
        exec:
          command:
            - buildctl
            - debug
            - workers
        initialDelaySeconds: 5
        periodSeconds: 30
      livenessProbe:
        exec:
          command:
            - buildctl
            - debug
            - workers
        initialDelaySeconds: 5
        periodSeconds: 30
      securityContext:
        privileged: true