---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-webapp
  labels:
    app: backend
    project: demo
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: api
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
      - name: ts-example
        image: piky/ts-example
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 1
          periodSeconds: 10
