apiVersion: v1
kind: Pod
metadata:
  name: agent-nodejs
  labels:
      jenkins-agent: jnlp-agent-nodejs
spec:
  containers:
    - name: nodejs
      image: piky/jnlp-agent-nodejs:latest
      command:
        - cat
      tty: true